# Generated by Django 6.0.2 on 2026-04-25 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_field_updates_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='planting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
